//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemonstration_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAddressTable
    {
        public int AddressId { get; set; }
        public int EmployeeId { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
    
        public virtual EmployeeTable EmployeeTable { get; set; }
    }
}
